name: Auto Commit

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:     # Allows manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Explicitly allows pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update file with timestamp
        run: |
          echo "Last auto-commit: $(date -u)" > auto.txt

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Auto-commit: $(date -u)"
          git push
